server:
  port: 8179 #端口
spring:
  application:
    name: zuul-server #服务名称
  main:
    allow-bean-definition-overriding: true #忽略同名bean

hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 200
      queueSizeRejectionThreshold: 150
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 80000

ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000
zuul:
#  retryable: true
#  add-host-header: true
  ignoredServices: "*"
#  sensitiveHeaders: "*"
  host:
    socket-timeout-millis: 15000
    connect-timeout-millis: 15000
  routes:
    api:
      path: /api/**
      serviceId: service-api
    user:
      path: /user/**
      serviceId: service-user
    order:
      path: /order/**
      serviceId: service-order
  #zuul懒加载导致第一次请求延迟
  ribbon:
    eager-load:
      enabled: true
      clients: service-api

#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://127.0.0.1:8179/doc.html


logging:
  config: classpath:log4j2.xml


