spring:
  main:
    #忽略同名bean
    allow-bean-definition-overriding: true

mybatis‐plus:
  typeAliasesPackage: com.aomi.pay.entity
  mapper‐locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    global-config:
#      #逻辑已删除值（默认为1）
#      logic-delete-value: 1
#      #逻辑已删除值（默认为0）
#      logic-not-delete-value: 0
#    枚举包扫描

logging:
  config: classpath:log4j2.xml
