#加密秘钥版本号
key-version: AES.1
#调用地址
api-url: https://payapi.imipay.com
#敏感信息加密秘钥
key: DhkBuSzwoA2gwusyl4LdsQ==
#环讯平台分配的应用id
up-appid: 7133020439161736211
#签名秘钥
app-secret: V6jLaak932pBK7CxtQJQ4IREi3M5LZqB
#机构应用id
inst-id: '027014'
#版本号
version: 1.0.0

#调用路径
api_route:
  pay:
    #扫码支付
    online_trade: /online/trade
    #订单查询
    online_query: /online/query