#支付参数配置
pay:
  hx:
    #支付回调地址
    notify_url: https://notify.yxwl.wang/payNotify
    #结算周期
    settle_type: 2
    #订单失效时间 分钟
    exprice: 60

#支付宝参数
alipay:
  #网关
  url: https://openapi.alipay.com/gateway.do
  #appid
  appid: 2021001168632988
  #私钥
  private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCNENyB8niHvexRzl/0c+SMHg9ZbT3iKkkDvqH0IaIpcXn6lxpvn6HPLRp40p0v0D1/fJJCPjjJMlBZz4yLGcTvC5/oL92ix6PaY4piySx+JqJ+zkS6YulDodATtgzBr60Em3vcWwFSq+ne6KNwb6nyBhUCIz+UZcWWH+X872+r8djZAeWVwa06zAbjeExTja+0DpuM4cbpeiHu6qkjbxQM7JX/Bb79V1uP5BqXWKIr9P8DDXaplEbrLqmLrpd+uMXrohIDfLTk4zdAjqOvLfnCb0gAk/RcbvZIdCcYszuVbCwUT8UnvuAW9wc8jMNAbgVLIAbCD/qtbF30mxWny8ZFAgMBAAECggEBAImh9+L5dcvK6/VtC4XwRP7InWU9BnHRm+eBaXZOEm+o/cAXCX37G96NPRTBOQfbfwURv4nON41l/6uAqrlU7SXmC6B4gyA89IsxL2XurfBvNX/PNJM9yiVojSGOL6gSBRdHtHNsfz/v54DLLhuXdxJiCMFLLs9U9JDiknxUCHqTPAM8JS0o9nXe1yBi72yk3GNDZC0nGr6hIxKXhtl9esTzKOmeIRi5l0jRS1+A91dI+cZLgKX2q3Qk7xo0GOzDKtnOuVQ8T1LGAeH0mc5TMgGdouxazFZ6rywl+csK5I2DKTlILZzo+TBnvWHISkD0VajQ8XYfxmTNcVca5hlzmckCgYEA/aKI5KrJgHWHZfIJykoT+wGKXex50kNGhWopqbeZ/0LlT2FKcnqYx2Y+RTH52v0vMkGvyLfTT+/tBiuEWZBRmWy7wIDiHK1zBAkhQYFWjMj6/os1Wb6sRTpS6JYt7iASPxtVnvVyuCYsvwDOuuZ3Ft/D+WVlCDE1Qjye3nPBBqsCgYEAjmGbbNWdD9Q6esBnKoLpjhoTRs8JA5eCPm0nc+w4KXZSIuBrfuWfkQ3iYjly9gIVODUnXMr+TX0VoiFFbhdqc0ixN70trHReQNAfrI4FSjg9llQDLq5rZd0c43J+1ZaRB1a0WKt8Jq+ZcFHR05AG96e3QwGezFIAbRggnJ8uJs8CgYEAz+LseSBS0GuEctaTl65n+hAlLR6qKuDhaHC/fU/zdPmLoiiIMJSzrJvs5iI0PH3QtUyJm+av2JE6oRgB/rb/atVofjwlGIRCBUjGbT5phjMlJoVLUSerY4KOefy94LOAwSDSaNudD7qaamNrDl3ftmvp4Pxudux+TrAJNyOBTskCgYB1b66JsxtL3gmqC55MIxROn9U8dzGBI+tKYC/FXpXoJO6UU7R2QyE8vE34JFhc7tTfun/P+qKL+VrpkjW5G1ky40dAqSnN72F6Ze9qHO3iDMdHgd3qF/T/XMQiGeLhesH+YpZ3+GF7ayTMzr+Zl1cX197BRsnaztwJH3hulqCzYwKBgQC1H4JnOeJ4crzT+N/oI2h3eJZOtZ+PxrVetMDHqgkgbcFaRJfBrGVh0Pk/goQezBUKDhbX4/WOrTEWcYoPs33V/7Zv6kjkldP3Phvzzvl7/Y0+yiLTIVzBx1E0sP4wyKIPYd2QyOtrTvX7abAqMDoOGSJisr5vnyvuBTFlJ5ekuQ==
  #请求方式
  format: json
  #编码格式
  charset: utf-8
  #公钥
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz6E8KWmPjRfxtg1X3twnPdkRUd6rwCsCtUfI8OTsyz+Ir3cPKd5yXhnAdhUS14ODXGCadCRTbH7MHTialAKsiab0tEE0BM6/MT2iYYU5pbx978HNk/HTOqFwnz1eh8XpAWe+BQS4aIujmOIxZ49IqixsLTA3GC60aeLnqKwNtZ3TXdjmVWEF02dKNdVV0Zaq45LAOnYCjQF1lRbt4qHaYCoG1fqNO+vob1bdtv/ubXHcfgVOh+nWa/c25Kq0Ne90CRfNj3z9IRiTJoN7lssMK6wrbwTmzqcs3E9jnkFcr0W2SL1InIpTNY15XOOYnGAHFeoSrOJMYEeEjyD3NIc/swIDAQAB
  #签名方式
  sign_type: RSA2

#微信参数
wx:
  #appid
  appid: wxeb1b1558437e9b12
  #secret
  secret: c9c984b5cdd3725790b92e7417c268df