zuul:
  #  retryable: true
  #  add-host-header: true
  # ignoredServices: "*"
  #sensitiveHeaders: "*"
  sensitiveHeaders:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 30000
  routes:
    api:
      path: /api/**
      serviceId: service-api
    qr:
      path: /qr/**
      serviceId: service-h5
    pay:
      path: /pay/**
      serviceId: service-pay
  add-host-header: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    #取消懒加载
    enabled: true
    clients: service-api, service-pay,service-mq

hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 200
      queueSizeRejectionThreshold: 150
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 40000

logging:
  config: classpath:log4j2.xml
