server:
  port: 8000 #端口
spring:
  application:
    name: back-zuul-server #服务名称

hystrix:
  threadpool:
    default:
      coreSize: 300
      maxQueueSize: 200
      queueSizeRejectionThreshold: 150
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 15000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000



zuul:
#  retryable: true
#  add-host-header: true
#  ignoredServices: "*"
#  sensitiveHeaders: "*"
  host:
    socket-timeout-millis: 15000
    connect-timeout-millis: 15000
  routes:
    user:
      path: /user/**
      serviceId: service-user
      strip-prefix: false
    order:
      path: /order/**
      serviceId: service-order
      strip-prefix: false
    item:
      path: /items/**
      serviceId: service-items
      strip-prefix: false
    payment:
      path: /payment/**
      serviceId: service-payment
      strip-prefix: false
    users:
      path: /app/user/**
      serviceId: service-user
      strip-prefix: false
    orders:
      path: /app/order/**
      serviceId: service-order
      strip-prefix: false
    items:
      path: /app/items/**
      serviceId: service-items
      strip-prefix: false
    payments:
      path: /app/payment/**
      serviceId: service-payment
      strip-prefix: false
    youhui:
      path: /youhui/**
      serviceId: service-user
      strip-prefix: false
    search:
      path: /search/**
      serviceId: service-search
      strip-prefix: false
#配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


logging:
  config: classpath:log4j2.xml


